# Generated by Django 5.1.6 on 2025-03-06 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tape', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tape',
            name='user',
        ),
    ]
