# Generated by Django 5.1.6 on 2025-03-09 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0002_remove_song_release_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='album_art_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
